// packages/ui-angular/src/match-row/match-row.component.ts
import { Component, Input, Output, EventEmitter, ViewEncapsulation } from '@angular/core';
import { CommonModule } from '@angular/common';

/**
 * MatchRowComponent — molecule. One result row in the GlobalSearch `ResultsPreview` panel.
 *
 * Layout: 40×40 avatar (gray surface, slotted icon) · a main line with the match ID
 * (semibold) + route on the left and a source badge on the right · a meta line of
 * Customer | Carrier | BOL cells separated by vertical dividers.
 *
 * Source Figma node: https://www.figma.com/design/vodiHJU38YWZYmTz81uOk7/Design-System---MCP?node-id=2460-2
 *
 * Usage:
 *   <od-match-row
 *     matchId="M-001"
 *     route="Chicago → Dallas"
 *     customer="Acme Corp"
 *     carrier="FastFreight"
 *     bol="BOL-999"
 *     sourceLabel="FourKites, Inc."
 *     sourceVariant="blue"
 *     (clicked)="onRowClick($event)"
 *   >
 *     <lucide-icon slot="icon" name="package"></lucide-icon>
 *   </od-match-row>
 */
@Component({
  standalone: true,
  imports: [CommonModule],
  selector: 'od-match-row',
  encapsulation: ViewEncapsulation.None,
  template: `
    <div [class]="hostClasses" (click)="clicked.emit($event)" role="button" tabindex="0">
      <div class="match-row__avatar" aria-hidden="true">
        <ng-content select="[slot=icon]" />
      </div>

      <div class="match-row__body">
        <div class="match-row__route">
          <span class="match-row__route-text text-label-xs-regular">
            <span class="text-label-xs-semibold">{{ matchId }}</span>
            <span *ngIf="route">&nbsp;{{ route }}</span>
          </span>
          <span [class]="sourceBadgeClasses">{{ sourceLabel }}</span>
        </div>

        <div class="match-row__meta text-label-xs-regular">
          <span class="match-row__meta-cell match-row__meta-cell--divider">
            <span>Customer:</span>
            <span>{{ customer }}</span>
          </span>
          <span class="match-row__meta-cell match-row__meta-cell--divider">
            <span>Carrier:</span>
            <span>{{ carrier }}</span>
          </span>
          <span [class]="bolCellClasses">
            <span>BOL:</span>
            <span>{{ bol }}</span>
          </span>
          <span *ngIf="shipmentId" class="match-row__meta-cell">
            <span>Shipment #:</span>
            <span>{{ shipmentId }}</span>
          </span>
        </div>
      </div>
    </div>
  `,
})
export class MatchRowComponent {
  /** Unique match identifier shown in bold on the main line. */
  @Input() matchId = '';

  /** Route description shown next to the match ID. */
  @Input() route = '';

  /** Customer name shown in the meta line. */
  @Input() customer = '';

  /** Carrier name shown in the meta line. */
  @Input() carrier = '';

  /** Bill of Lading number shown in the meta line. */
  @Input() bol = '';

  /** Optional shipment ID shown in the meta line after BOL. */
  @Input() shipmentId = '';

  /** Label text for the source badge. */
  @Input() sourceLabel = 'FourKites, Inc.';

  /** Variant for the source badge — maps to `badge--blue` or `badge--purple`. */
  @Input() sourceVariant: 'blue' | 'purple' = 'blue';

  /** Emitted when the row is clicked. */
  @Output() clicked = new EventEmitter<MouseEvent>();

  get hostClasses(): string {
    return 'match-row';
  }

  get sourceBadgeClasses(): string {
    return `match-row__source badge badge--${this.sourceVariant}`;
  }

  get bolCellClasses(): string {
    return this.shipmentId
      ? 'match-row__meta-cell match-row__meta-cell--divider'
      : 'match-row__meta-cell';
  }
}

// packages/ui/src/MatchRow.jsx
import { Container, Package, Handshake } from 'lucide-react'
import { ICON_LG } from '@odyssey/tokens'
import Badge from './Badge.jsx'

const AVATAR_ICONS = {
  container: <Container {...ICON_LG} />,
  package: <Package {...ICON_LG} />,
  handshake: <Handshake {...ICON_LG} />,
}

/**
 * MatchRow — molecule. One result row in the GlobalSearch `ResultsPreview` panel.
 *
 * Layout: 40×40 avatar (gray surface, switchable icon) · a main line with the
 * match ID (semibold) + route (regular) on the left and a source Badge on the
 * right · a meta line of Customer | Carrier | BOL cells separated by vertical
 * dividers.
 *
 * Figma master: `MatchRow` set `2460:2` on Components-Molecules.
 * The avatar icon is a switchable INSTANCE_SWAP slot (placeholder-20 in Figma);
 * in code it defaults to a neutral `Package` glyph — pass `icon` to override.
 * The source pill is a real `Badge` instance (`blue` default; `purple` for EDI feeds).
 *
 * `onClick` makes the whole row a selectable button (adds a hover affordance).
 */
export default function MatchRow({
  matchId,
  route,
  customer,
  carrier,
  bol,
  shipmentId,
  source = { label: 'FourKites, Inc.', variant: 'blue' },
  icon,
  iconType,
  onClick,
  className = '',
  ...rest
}) {
  return (
    <div
      className={`match-row ${className}`.trim()}
      onClick={onClick}
      role={onClick ? 'button' : undefined}
      tabIndex={onClick ? 0 : undefined}
      {...rest}
    >
      <div className="match-row__info">
        <span className="match-row__avatar" aria-hidden="true">
          {icon || AVATAR_ICONS[iconType] || AVATAR_ICONS.container}
        </span>
        <div className="match-row__details">
          <div className="match-row__main">
            <span className="match-row__location text-label-xs-regular">
              <span className="text-label-xs-semibold">{matchId}</span>
              {route ? <span>&nbsp;{route}</span> : null}
            </span>
            {source && <Badge variant={source.variant}>{source.label}</Badge>}
          </div>
          <div className="match-row__meta text-label-xs-regular">
            <span className="match-row__meta-cell match-row__meta-cell--divider">
              <span>Customer:</span>
              <span>{customer}</span>
            </span>
            <span className="match-row__meta-cell match-row__meta-cell--divider">
              <span>Carrier:</span>
              <span>{carrier}</span>
            </span>
            <span className={`match-row__meta-cell${shipmentId ? ' match-row__meta-cell--divider' : ''}`}>
              <span>BOL:</span>
              <span>{bol}</span>
            </span>
            {shipmentId && (
              <span className="match-row__meta-cell">
                <span>Shipment #:</span>
                <span>{shipmentId}</span>
              </span>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
