// packages/ui-angular/src/widget/widget.component.ts
import { Component, Input, Output, EventEmitter, ViewEncapsulation } from '@angular/core';
import { CommonModule } from '@angular/common';
import { IconButtonGhostComponent } from '../icon-button-ghost/icon-button-ghost.component';
import { WidgetMetricRowComponent } from '../widget-metric-row/widget-metric-row.component';
import { WidgetPieChartComponent } from '../widget-pie-chart/widget-pie-chart.component';
import { WidgetCtaRowComponent } from '../widget-cta-row/widget-cta-row.component';

export type WidgetVariant = '1x' | '2x' | '3x' | '3xChart' | '3xCta';

export interface WidgetMetricRow {
  label: string;
  value: string;
  indicatorColor?: string;
}

export interface WidgetCtaRowData {
  label: string;
}

export interface WidgetChartSegment {
  value: number;
  color: string;
}

/**
 * WidgetComponent — organism. Unified Home dashboard widget with 5 layout variants.
 *
 * Variants:
 *   1x       — Clickable value + label block with inline arrow.
 *   2x       — Large value + label + optional pie chart (donut) beside it.
 *   3x       — Vertical list of metric rows (label + value badge).
 *   3xChart  — Large pie chart + value + label header + metric row legend.
 *   3xCta    — Vertical list of call-to-action link rows (no chart).
 *
 * Source Figma node: https://www.figma.com/design/vodiHJU38YWZYmTz81uOk7/Design-System---MCP?node-id=1825-7
 *
 * Usage:
 *   <od-widget variant="2x" title="Total Orders" value="1,234" label="This month"
 *              [chartSegments]="segments" percentage="42%"
 *              (closeClicked)="onClose()">
 *     <span slot="domainIcon">…</span>
 *   </od-widget>
 */
@Component({
  standalone: true,
  imports: [
    CommonModule,
    IconButtonGhostComponent,
    WidgetMetricRowComponent,
    WidgetPieChartComponent,
    WidgetCtaRowComponent,
  ],
  selector: 'od-widget',
  encapsulation: ViewEncapsulation.None,
  template: `
    <div [class]="hostClasses">

      <!-- ─── Header ─────────────────────────────────────────────────────── -->
      <header class="widget__header">
        <div class="widget__header-title">
          <!-- Grip icon — shown in edit mode or when showGrip=true -->
          <ng-container *ngIf="showGrip || editMode">
            <svg
              class="widget__grip"
              width="24" height="24" viewBox="0 0 24 24"
              fill="none" aria-hidden="true"
            >
              <circle cx="9" cy="6"  r="1.5" fill="currentColor"/>
              <circle cx="9" cy="12" r="1.5" fill="currentColor"/>
              <circle cx="9" cy="18" r="1.5" fill="currentColor"/>
              <circle cx="15" cy="6"  r="1.5" fill="currentColor"/>
              <circle cx="15" cy="12" r="1.5" fill="currentColor"/>
              <circle cx="15" cy="18" r="1.5" fill="currentColor"/>
            </svg>
          </ng-container>

          <!-- Domain icon slot — container style differs by variant -->
          <ng-container *ngIf="variant === '3x' || variant === '3xChart'">
            <span class="widget__domain-icon-container">
              <ng-content select="[slot=domainIcon]" />
            </span>
          </ng-container>
          <ng-container *ngIf="variant === '1x' || variant === '2x'">
            <span class="widget__domain-icon">
              <ng-content select="[slot=domainIcon]" />
            </span>
          </ng-container>

          <!-- Title — typography class varies by variant -->
          <span [class]="titleClasses">{{ title }}</span>
        </div>

        <!-- Close button — shown in edit mode (→ removeClicked) or when closeClicked is observed -->
        <od-icon-button-ghost
          *ngIf="editMode || closeClicked.observed"
          ariaLabel="Remove widget"
          class="widget__close"
          (clicked)="editMode ? removeClicked.emit() : closeClicked.emit()"
        >
          <!-- X icon -->
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none"
            stroke="currentColor" stroke-width="2"
            stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <line x1="18" y1="6" x2="6" y2="18"/>
            <line x1="6" y1="6" x2="18" y2="18"/>
          </svg>
        </od-icon-button-ghost>
      </header>

      <!-- ─── Content (variant-switched) ────────────────────────────────── -->
      <div [ngSwitch]="variant">

        <!-- 1x: clickable value + label block -->
        <ng-template ngSwitchCase="'1x'">
          <button
            type="button"
            class="widget__content widget__content--1x"
            (click)="goToClicked.emit()"
            [disabled]="!goToClicked.observed"
          >
            <span class="widget__value-row">
              <span class="text-display-3xl-semibold widget__value">{{ value }}</span>
              <!-- Arrow right icon -->
              <svg class="widget__inline-arrow" width="16" height="16" viewBox="0 0 16 16"
                fill="none" aria-hidden="true">
                <path d="M3 8h10M9 4l4 4-4 4"
                  stroke="currentColor" stroke-width="1.5"
                  stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
            </span>
            <span class="text-label-sm-regular widget__label">{{ label }}</span>
          </button>
        </ng-template>

        <!-- 2x: value + label + optional pie chart -->
        <ng-template ngSwitchCase="'2x'">
          <div class="widget__content widget__content--2x">
            <div class="widget__data-container">
              <span class="text-display-3xl-semibold widget__value">{{ value }}</span>
              <span class="text-label-sm-medium widget__label">{{ label }}</span>
            </div>
            <od-widget-pie-chart
              *ngIf="showChart"
              size="md"
              [segments]="chartSegments"
              [total]="chartTotal"
              [showCenterText]="!!percentage"
              [centerText]="percentage"
            ></od-widget-pie-chart>
          </div>
        </ng-template>

        <!-- 3x: vertical metric row list -->
        <ng-template ngSwitchCase="'3x'">
          <div class="widget__content widget__content--3x">
            <od-widget-metric-row
              *ngFor="let row of rows"
              [label]="row.label"
              [value]="row.value"
              [showIndicator]="false"
            ></od-widget-metric-row>
          </div>
        </ng-template>

        <!-- 3xChart: pie chart + metric row legend -->
        <ng-template ngSwitchCase="'3xChart'">
          <div class="widget__content widget__content--3xChart">
            <div class="widget__chart-section">
              <div class="widget__info-container">
                <span class="text-display-4xl-semibold widget__value">{{ value }}</span>
                <span class="text-label-sm-medium widget__label">{{ label }}</span>
              </div>
              <od-widget-pie-chart
                size="lg"
                [segments]="chartSegments"
                [total]="chartTotal"
              ></od-widget-pie-chart>
            </div>
            <div class="widget__data-section">
              <od-widget-metric-row
                *ngFor="let row of rows"
                [label]="row.label"
                [value]="row.value"
                [showIndicator]="true"
                [indicatorColor]="row.indicatorColor || ''"
              ></od-widget-metric-row>
            </div>
          </div>
        </ng-template>

        <!-- 3xCta: call-to-action link row list -->
        <ng-template ngSwitchCase="'3xCta'">
          <div class="widget__content widget__content--3xCta">
            <od-widget-cta-row
              *ngFor="let row of ctaRows"
              [label]="row.label"
            ></od-widget-cta-row>
          </div>
        </ng-template>

      </div>

      <!-- ─── Footer "Go to" link — shown for 2x / 3x / 3xChart when wired ─ -->
      <ng-container *ngIf="variant !== '1x' && variant !== '3xCta' && goToLabel && goToClicked.observed">
        <button
          type="button"
          class="btn btn--link btn--sm widget__goto"
          (click)="goToClicked.emit()"
        >
          {{ goToLabel }}
          <!-- Arrow right icon -->
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true">
            <path d="M3 8h10M9 4l4 4-4 4"
              stroke="currentColor" stroke-width="1.5"
              stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
        </button>
      </ng-container>

    </div>
  `,
})
export class WidgetComponent {
  /** Layout variant. Determines which content template is rendered. */
  @Input() variant: WidgetVariant = '1x';

  /** Widget title shown in the header. */
  @Input() title = '';

  /** Whether to render the drag-grip handle in the header. */
  @Input() showGrip = false;

  /** Primary metric value (1x, 2x, 3xChart). */
  @Input() value = '';

  /** Metric label / description below the value. */
  @Input() label = '';

  /** Percentage text shown as pie chart center label (2x). */
  @Input() percentage = '';

  /** Metric rows for 3x and 3xChart variants. */
  @Input() rows: WidgetMetricRow[] = [];

  /** Call-to-action rows for 3xCta variant. */
  @Input() ctaRows: WidgetCtaRowData[] = [];

  /** Pie chart segments for 2x and 3xChart variants. */
  @Input() chartSegments: WidgetChartSegment[] = [];

  /** Optional explicit denominator for the pie chart. Defaults to segment sum. */
  @Input() chartTotal: number | null = null;

  /** Whether the pie chart is shown (2x variant only). */
  @Input() showChart = true;

  /** Label for the footer "go to" link button. */
  @Input() goToLabel = '';

  /**
   * Edit mode: forces grip on, shows remove button wired to `removeClicked`,
   * and adds the `widget--edit-mode` modifier class.
   */
  @Input() editMode = false;

  /** Emitted when the header close button is clicked (normal mode). */
  @Output() closeClicked = new EventEmitter<void>();

  /** Emitted when the footer "go to" button is clicked. */
  @Output() goToClicked = new EventEmitter<void>();

  /** Emitted when the header close button is clicked in edit mode. */
  @Output() removeClicked = new EventEmitter<void>();

  get hostClasses(): string {
    return [
      'widget',
      `widget--${this.variant}`,
      this.editMode ? 'widget--edit-mode' : '',
    ]
      .filter(Boolean)
      .join(' ');
  }

  get titleClasses(): string {
    if (this.variant === '1x') return 'widget__title text-label-xs-medium';
    if (this.variant === '2x') return 'widget__title text-label-sm-medium';
    return 'widget__title text-heading-lg-medium'; // 3x / 3xChart / 3xCta
  }
}

// packages/ui/src/Widget.jsx
import { ArrowRight, GripVertical, X } from 'lucide-react'
import { ICON_MD, ICON_LG } from '@odyssey/tokens'
import Button from './Button.jsx'
import IconButtonGhost from './IconButtonGhost.jsx'
import WidgetMetricRow from './WidgetMetricRow.jsx'
import WidgetPieChart from './WidgetPieChart.jsx'
import WidgetCtaRow from './WidgetCtaRow.jsx'

/**
 * Widget — molecule. Unified Home dashboard widget with 5 variants (1x / 2x / 3x / 3xChart / 3xCta).
 *
 * The shell (header + footer) and content are intentionally bundled into one component:
 * resizing in the UI is a `variant` prop change, not a component swap. Figma mirrors this
 * as a single component set with `Variant=1x|2x|3x|3xChart|3xCta`.
 *
 * Common props:  variant, title, domainIcon, showGrip, onClose, onGoToClick, goToLabel
 * 1x:            value, label                                          (Header arrow takes you to source)
 * 2x:            value, label, percentage, chartSegments               (small donut beside metric)
 * 3x:            rows (array of { label, value, indicatorColor? })     (4-6 rows of stats)
 * 3xChart:       value, label, rows, chartSegments                     (donut + multi-row legend)
 * 3xCta:         ctaRows (array of { icon, label, onClick })           (4 link rows, no chart, no data)
 *
 * `rows` items: { label, value, indicatorColor?, onClick? }
 * `chartSegments` items: { value, color } — color is a Chart/* token (e.g. 'var(--chart-1)')
 * `ctaRows` items: { icon (ReactNode), label (string), onClick (fn) } — call-to-action links.
 *   The 3xCta shell drops outer padding so rows can sit flush against the divider lines.
 */
export default function Widget({
  variant = '1x',
  title = '',
  domainIcon,
  // Grip + close button are edit-mode-only affordances. Default off; consumers
  // in an "edit a view profile" mode pass showGrip={true} + onClose={fn} to enable.
  showGrip = false,
  onClose,
  onGoToClick,
  goToLabel,
  // Content props (used per variant)
  value,
  label,
  percentage,
  rows = [],
  ctaRows = [],
  chartSegments = [],
  // Optional denominator for the chart. Use for 2x single-data views where the
  // segment value (e.g. 42) represents a fraction of an implied whole (e.g. 100),
  // so the chart shows 42% filled + 58% chart-rest. Omit for 3xChart where the
  // segments already sum to the total.
  chartTotal,
  // 2x only — hide the donut for stat-only widgets (e.g. Users Enrolled: 142
  // with no percentage). Maps to the Figma `Show chart` BOOLEAN on WidgetContent 2x.
  showChart = true,
  // Edit mode — Home dashboard "Add Widgets" flow. Forces grip on, dims CTAs to
  // non-interactive, and overlays a top-right close button wired to onRemove.
  editMode = false,
  onRemove,
  className = '',
  ...rest
}) {
  const cls = `widget widget--${variant} ${className}`.trim()
  const editAttrs = editMode ? { 'data-edit-mode': 'true' } : {}
  return (
    <div className={cls} {...editAttrs} {...rest}>
      <Header
        variant={variant}
        title={title}
        domainIcon={domainIcon}
        showGrip={showGrip || editMode}
        onClose={editMode ? onRemove : onClose}
      />
      <Content
        variant={variant}
        value={value}
        label={label}
        percentage={percentage}
        rows={rows}
        ctaRows={ctaRows}
        chartSegments={chartSegments}
        chartTotal={chartTotal}
        showChart={showChart}
        onGoToClick={onGoToClick}
      />
      {variant !== '1x' && variant !== '3xCta' && onGoToClick && goToLabel && (
        <Button
          variant="link"
          size="sm"
          iconRight={<ArrowRight {...ICON_MD} />}
          onClick={onGoToClick}
        >
          {goToLabel}
        </Button>
      )}
    </div>
  )
}

function Header({ variant, title, domainIcon, showGrip, onClose }) {
  const titleClass =
    variant === '1x' ? 'text-label-xs-medium'
    : variant === '2x' ? 'text-label-sm-medium'
    : 'text-heading-lg-medium' // 3x / 3xChart
  const showDomainIconContainer = variant === '3x' || variant === '3xChart'
  const showInlineDomainIcon = (variant === '1x' || variant === '2x') && domainIcon

  return (
    <header className="widget__header">
      <div className="widget__header-title">
        {showGrip && <GripVertical {...ICON_LG} className="widget__grip" aria-hidden="true" />}
        {showDomainIconContainer ? (
          <span className="widget__domain-icon-container">
            {domainIcon}
          </span>
        ) : (
          showInlineDomainIcon && <span className="widget__domain-icon">{domainIcon}</span>
        )}
        <span className={`widget__title ${titleClass}`}>{title}</span>
      </div>
      {onClose && (
        <IconButtonGhost
          icon={<X {...ICON_LG} aria-hidden="true" />}
          onClick={onClose}
          ariaLabel="Remove widget"
        />
      )}
    </header>
  )
}

function Content({ variant, value, label, percentage, rows, ctaRows, chartSegments, chartTotal, showChart, onGoToClick }) {
  if (variant === '1x') {
    return (
      <button
        type="button"
        className="widget__content widget__content--1x"
        onClick={onGoToClick}
        disabled={!onGoToClick}
      >
        <span className="widget__value-row">
          <span className="text-display-3xl-semibold widget__value">{value}</span>
          <ArrowRight {...ICON_MD} className="widget__inline-arrow" aria-hidden="true" />
        </span>
        <span className="text-label-sm-regular widget__label">{label}</span>
      </button>
    )
  }
  if (variant === '2x') {
    return (
      <div className="widget__content widget__content--2x">
        <div className="widget__data-container">
          <span className="text-display-3xl-semibold widget__value">{value}</span>
          <span className="text-label-sm-medium widget__label">{label}</span>
        </div>
        {showChart && (
          <WidgetPieChart segments={chartSegments} total={chartTotal} centerText={percentage} size="md" />
        )}
      </div>
    )
  }
  if (variant === '3x') {
    return (
      <div className="widget__content widget__content--3x">
        {rows.map((row, i) => (
          <WidgetMetricRow
            key={i}
            label={row.label}
            value={row.value}
            showIndicator={false}
            onClick={row.onClick}
          />
        ))}
      </div>
    )
  }
  if (variant === '3xCta') {
    return (
      <div className="widget__content widget__content--3xCta">
        {ctaRows.map((row, i) => (
          <WidgetCtaRow
            key={i}
            icon={row.icon}
            label={row.label}
            onClick={row.onClick}
          />
        ))}
      </div>
    )
  }
  if (variant === '3xChart') {
    return (
      <div className="widget__content widget__content--3xChart">
        <div className="widget__chart-section">
          <div className="widget__info-container">
            <span className="text-display-4xl-semibold widget__value">{value}</span>
            <span className="text-label-sm-medium widget__label">{label}</span>
          </div>
          <WidgetPieChart segments={chartSegments} total={chartTotal} size="lg" />
        </div>
        <div className="widget__data-section">
          {rows.map((row, i) => (
            <WidgetMetricRow
              key={i}
              label={row.label}
              value={row.value}
              showIndicator={true}
              indicatorColor={row.indicatorColor}
              onClick={row.onClick}
            />
          ))}
        </div>
      </div>
    )
  }
  return null
}
