// packages/ui/src/WidgetsLeftMenu.jsx
import { Fragment } from 'react'
import SearchField from './SearchField.jsx'
import MenuRow from './MenuRow.jsx'
import MenuDropdown from './MenuDropdown.jsx'

/**
 * WidgetsLeftMenu — organism. Catalog panel: title + search + collapsible groups of items.
 * Library-pure: accepts an optional `renderItem` render-prop so consumers can wrap each
 * item with their DnD adapter (e.g. dnd-kit's useSortable) without this package depending on it.
 */
export default function WidgetsLeftMenu({
  title = 'Metrics library',
  groups = [],
  searchValue = '',
  onSearchChange,
  collapsedGroupIds,
  onToggleGroup,
  onItemClick,
  renderItem,
  className = '',
  ...rest
}) {
  const collapsedSet =
    collapsedGroupIds instanceof Set
      ? collapsedGroupIds
      : new Set(collapsedGroupIds || [])

  const query = (searchValue || '').toLowerCase().trim()
  const filteredGroups = groups
    .map((g) => {
      const items = query
        ? (g.items || []).filter((it) => it.label.toLowerCase().includes(query))
        : (g.items || [])
      return { ...g, items }
    })
    .filter((g) => g.items.length > 0)

  return (
    <div
      className={`widgets-left-menu flex flex-col ${className}`.trim()}
      style={{
        width: 240,
        height: '100%',
        background: 'var(--white)',
        boxShadow: 'var(--shadow-panel)',
      }}
      {...rest}
    >
      <div
        className="flex items-center"
        style={{
          height: 48,
          padding: 'var(--spacing-4)',
          borderBottom: '1px solid var(--border-subtle)',
        }}
      >
        <span
          className="text-label-xs-semibold"
          style={{ color: 'var(--text-primary)' }}
        >
          {title}
        </span>
      </div>

      <div
        style={{
          padding: 'var(--spacing-3) var(--spacing-4)',
        }}
      >
        <SearchField
          value={searchValue}
          onChange={onSearchChange}
          placeholder="Search"
        />
      </div>

      <div className="flex flex-col" style={{ overflowY: 'auto' }}>
        {filteredGroups.map((group) => {
          const collapsed = collapsedSet.has(group.id)
          return (
            <MenuDropdown
              key={group.id}
              title={group.title}
              expanded={!collapsed}
              onToggle={() => onToggleGroup?.(group.id)}
            >
              {group.items.map((item) => {
                const defaultNode = (
                  <MenuRow
                    key={item.id}
                    label={item.label}
                    onClick={() => onItemClick?.(item.id, group.id)}
                  />
                )
                if (renderItem) {
                  return (
                    <Fragment key={item.id}>
                      {renderItem(item, group, defaultNode)}
                    </Fragment>
                  )
                }
                return defaultNode
              })}
            </MenuDropdown>
          )
        })}
      </div>
    </div>
  )
}

// packages/ui-angular/src/widgets-left-menu/widgets-left-menu.component.ts
import { Component, Input, Output, EventEmitter, ViewEncapsulation } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SearchFieldComponent } from '../search-field/search-field.component';
import { MenuDropdownComponent } from '../menu-dropdown/menu-dropdown.component';
import { MenuRowComponent } from '../menu-row/menu-row.component';

export interface WidgetsGroup {
  title: string;
  items: string[];
}

/**
 * WidgetsLeftMenuComponent — organism. Side-panel widget catalog.
 * Renders a fixed-width panel with: title header, search field, and a list of
 * collapsible `MenuDropdown` groups each containing `MenuRow` items.
 *
 * Source Figma node: https://www.figma.com/design/vodiHJU38YWZYmTz81uOk7/Design-System---MCP?node-id=1961-393
 *
 * Usage:
 *   <od-widgets-left-menu
 *     title="Metrics library"
 *     [searchValue]="query"
 *     [groups]="groups"
 *     (searchChange)="query = $event"
 *   ></od-widgets-left-menu>
 */
@Component({
  standalone: true,
  imports: [
    CommonModule,
    SearchFieldComponent,
    MenuDropdownComponent,
    MenuRowComponent,
  ],
  selector: 'od-widgets-left-menu',
  encapsulation: ViewEncapsulation.None,
  template: `
    <div
      class="widgets-left-menu flex flex-col"
      style="width: 240px; height: 100%; background: var(--white); box-shadow: var(--shadow-panel);"
    >
      <!-- Header -->
      <div
        class="widgets-left-menu__header flex items-center"
        style="height: 48px; padding: var(--spacing-4); border-bottom: 1px solid var(--border-subtle);"
      >
        <span class="text-label-xs-semibold" style="color: var(--text-primary);">
          {{ title }}
        </span>
      </div>

      <!-- Search -->
      <div
        class="widgets-left-menu__search"
        style="padding: var(--spacing-3) var(--spacing-4);"
      >
        <od-search-field
          [value]="searchValue"
          placeholder="Search"
          (valueChange)="searchChange.emit($event)"
          (cleared)="searchChange.emit('')"
        ></od-search-field>
      </div>

      <!-- Groups -->
      <div class="widgets-left-menu__groups flex flex-col" style="overflow-y: auto;">
        <od-menu-dropdown
          *ngFor="let group of filteredGroups; trackBy: trackByTitle"
          [title]="group.title"
          [expanded]="isExpanded(group.title)"
          (toggled)="onToggle(group.title)"
        >
          <od-menu-row
            *ngFor="let item of group.items"
            [label]="item"
          ></od-menu-row>
        </od-menu-dropdown>
      </div>
    </div>
  `,
})
export class WidgetsLeftMenuComponent {
  /** Panel heading shown at the top. */
  @Input() title = '';

  /** Current controlled search value. */
  @Input() searchValue = '';

  /** Array of collapsible groups, each with a title and list of item label strings. */
  @Input() groups: WidgetsGroup[] = [];

  /** Emitted with the new string value whenever the search input changes. */
  @Output() searchChange = new EventEmitter<string>();

  /** Tracks which group titles are collapsed. */
  private collapsedTitles = new Set<string>();

  /** Filters groups and items based on the current searchValue. */
  get filteredGroups(): WidgetsGroup[] {
    const query = (this.searchValue || '').toLowerCase().trim();
    if (!query) return this.groups;
    return this.groups
      .map((g) => ({
        title: g.title,
        items: g.items.filter((item) => item.toLowerCase().includes(query)),
      }))
      .filter((g) => g.items.length > 0);
  }

  isExpanded(title: string): boolean {
    return !this.collapsedTitles.has(title);
  }

  onToggle(title: string): void {
    if (this.collapsedTitles.has(title)) {
      this.collapsedTitles.delete(title);
    } else {
      this.collapsedTitles.add(title);
    }
  }

  trackByTitle(_index: number, group: WidgetsGroup): string {
    return group.title;
  }
}
